### ISSUE TITLE
SDL_SCANCODE_TO_KEYCODE cannot be used in runtime

### ISSUE THREAD

**Issue by GoaLitiuM** [BindBC/bindbc-sdl#12]
Typically ``SDL_SCANCODE_TO_KEYCODE`` is expected to be a function/macro which can be called during runtime, but as it's defined as a compile-time constant, it cannot be used in a following scenario:
```d
SDL_Scancode scancode = SDL_Scancode.SDL_SCANCODE_UNKNOWN;
SDL_SCANCODE_TO_KEYCODE(scancode);
```
```
Error: template bindbc.sdl.bind.sdlkeycode.SDL_SCANCODE_TO_KEYCODE cannot deduce function from argument types !()(SDL_Scancode), candidates are:
bindbc-sdl\source\bindbc\sdl\bind\sdlkeycode.d(14,6): : bindbc.sdl.bind.sdlkeycode.SDL_SCANCODE_TO_KEYCODE(SDL_Scancode x)
```

**Comment by mdparker** [comment]
I thought it was only used to initialize the keycode enum values. I had no idea anyone would actually use it for anything else. I'll convert it to a function when I get the chance.

**Comment by GoaLitiuM** [comment]
I actually might be wrong here. Apparently there exists a function called ``SDL_GetKeyFromScancode`` which converts the given scancode to keycode using the mapping of the currently selected keyboard layout, so that seems to be the correct usage at least in my case.

**Comment by mdparker** [comment]
And that seems the proper way to do it, since it takes the keyboard layout into account. So I think we can leave this as it is.
