### ISSUE TITLE
Missing function: SDL_BlitSurface

### ISSUE THREAD

**Issue by rombankzero** [BindBC/bindbc-sdl#15]
The bindings seem to be missing SDL_BlitSurface(). I suspect it was overlooked because it's a macro'd alias for SDL_UpperBlit() in [SDL_surface.h](https://hg.libsdl.org/SDL/file/886b79177762/include/SDL_surface.h#l484). My workaround for now is to just call SDL_UpperBlit() directly, but SDL_BlitSurface() is part of the public API and should be covered.

**Comment by mdparker** [comment]
Actually, it was an oversight when I ported DerelictSDL2 over. I had that alias and the one for `SDL_BlitScaled` along with the handful of wrapper functions from the C headers in `sdl.d`:

https://github.com/DerelictOrg/DerelictSDL2/blob/master/source/derelict/sdl2/sdl.d#L40

I moved all of the functions over but overlooked the aliases. Both aliases are now declared in bindbc-sdl v0.9.1.

Thanks!
