### ISSUE TITLE
Error: undefined identifier SDL_GL_GetDrawableSize

### ISSUE THREAD

**Issue by joelcnz** [BindBC/bindbc-sdl#17]
It works with Derelict SDL.

**Comment by mdparker** [comment]
Unlike Derelict, bindbc splits the loading of different versions of a library into sections behind D `version` statements and only loads the lowest supported version by default. `SDL_GL_GetDrawableSize` was added to SDL in version 2.0.1, so to get it you need to set the version SDL_201 in your dub.json/sdl. Of course, if you use functions from any higher versions, you'll want to set those versions instead.

[Please see the README](https://github.com/BindBC/bindbc-sdl/blob/master/README.md), where this is all documented.

One strategy is to set the highest supported version(SDL_2010 at the moment, for SDL_210) and check the return value of load SDL against your minimum required version, e.g. (assuming SDL 2.0.1 is the minimum you require),

```d
auto loadedVersion = loadSDL();
if(ret < SDLSupport.sdl201) {
    // Report to the user that SDL 2.0.1 is required
}
```

This will ensure that the if condition will fail if you get `SDLSupport.noLibrary`,  `SDLSupport.badLibrary`, or a version of the library lower than the one you require (in this specific case `SDLSupport.sdl200`).

**Comment by joelcnz** [comment]
Thanks, got it working. Put "SDL_204" or "..2010" in dub.json versions.

**Comment by joelcnz** [comment]
I've been trying to convert cpp[0] source files to d files, but I'm still getting undefined errors. Have any tips on learning how to use SDL with D?

Maybe I should ask on dlang.org learning forum...

[0] http://lazyfoo.net/tutorials/SDL/index.php

**Comment by mdparker** [comment]
You don't need to convert the C++ to D. The C++-specific part is irrelevant. Just focus on how the tutorials make use of the SDL API.
