### ISSUE TITLE
SDL_WINDOWPOS_UNDEFINED_DISPLAY cannot be used at runtime

### ISSUE THREAD

**Issue by moon-chilled** [BindBC/bindbc-sdl#19]
It takes a template argument so it can't be used with compile-time unknown values.  Can you change it to a function?

Probably ditto for `SDL_WINDOWPOS_ISUNDEFINED`, `SDL_WINDOWPOS_CENTERED_DISPLAY`, and `SDL_WINDOWPOS_ISCENTERED`, but I haven't had need of those.

**Comment by mdparker** [comment]
Thanks! I didn't realize that's how they're supposed to be used. I thought I was making an improvement when I changed them from functions in Derelict to enum templates. I'll make the change as soon as I can.

**Comment by moon-chilled** [comment]
Yep, I have a runtime-configurable option to set which monitor the game window shows up on.

Thanks!

**Comment by mdparker** [comment]
Fixed in 0.14.0. Sorry for the delay.
