### ISSUE TITLE
SDL2_net

### ISSUE THREAD

**Issue by DannyArends** [BindBC/bindbc-sdl#22]
I migrated my project from Derelict to bindbc last weekend, which went very smooth. 
However, the SDL2_Net module / library I used in Derelict is not available for bindbc, are there any plans to port it?

**Comment by mdparker** [comment]
Just been waiting on someone to request it. I'll get it done this week.

**Comment by DannyArends** [comment]
Thanks Mike,

That would be awesome, a big thank you for your effort on the bindbc bindings, and all your hard work in the D community. The transition from derelict to bindbc was smooth as silk.

**Comment by mdparker** [comment]
Thanks so much :-)

SDL_net support is in 0.17.0. Other than ensuring it loads, it's currently untested. Please let me know if you have any problems with it.
