### ISSUE TITLE
atomicFence is not a template declaration

### ISSUE THREAD

**Issue by harakim** [BindBC/bindbc-sdl#26]
I have an old project that used the derelictSDL2 bindings on a different computer. I moved it to this computer and I can no longer figure out how to install derelictSDL. The pdf of instructions that I saved references files that do not even exist. So I decided I would try to update to the new bindings here in bindbc. 

My project uses make (as opposed to dub) because it's a fairly old project and I was inexperienced in D when I started writing it. So I downloaded bindbc and went to compile the project and got these results:

**Directory Listing for Reference**
Directory: C:\Program Files\D\dmd2\src\etc\bindbc-sdl

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         2/25/2021  12:08 AM                source
-a----         11/5/2020  10:17 PM             41 .gitignore
-a----         11/5/2020  10:17 PM            681 dub.sdl
-a----         11/5/2020  10:17 PM           1337 LICENSE_1_0.txt
-a----         11/5/2020  10:17 PM          17990 README.md

**This is the command that I ran**
PS C:\Program Files\D\dmd2\src\etc\bindbc-sdl> dub build
Performing "debug" build using C:\Program Files\D\dmd2\windows\bin\dmd.exe for x86_64.
bindbc-sdl ~master: building configuration "dynamic"...
**source\bindbc\sdl\bind\sdlatomic.d(29,29): Error: template instance `atomicFence!()` atomicFence is not a template declaration, it is a function**
C:\Program Files\D\dmd2\windows\bin\dmd.exe failed with exit code 1.
PS C:\Program Files\D\dmd2\src\etc\bindbc-sdl>

Compiler Version:
**DMD32 D Compiler v2.087.0**

I saw this dependency was mentioned as optional to include in the readme and I will not be using SDL atomic directly. I am not that good at any of this stuff (bindings/D/dub). I figured this was an easy thing to correct, which is why I'm asking for help here. If this is not a simple issue to respond to, then I can try removing that dependency or start over with a dub project instead.

**Comment by mdparker** [comment]
I am unable to reproduce that with DMD 2.095.0, in either 32- or 64-bit. Going into the `bindbc-sdl` directory and running `dub build` compiles the package without error. Perhaps it has something to do with the compiler version. Can you upgrade to the latest?

**Comment by harakim** [comment]
I should have thought of that. Thanks for the quick response.
