### ISSUE TITLE
No library assertion failure

### ISSUE THREAD

**Issue by joelcnz** [BindBC/bindbc-sdl#31]
On macOS Big Sur M1 comes up with not supported - no library.

'''d
SDLSupport ret = loadSDL();
	if(ret != sdlSupport) {
		// Handle error. For most use cases, this is enough. The error handling API in
		// bindbc-loader can be used for error messages. If necessary, it's  possible
		// to determine the primary cause programmtically:

		if(ret == SDLSupport.noLibrary) {
			// SDL shared library failed to load
			assert(0, "no library");
		}
'''

**Comment by mdparker** [comment]
So install it?

**Comment by joelcnz** [comment]
Of course, I've installed it. I used Home Brew, that's worked before.

**Comment by mdparker** [comment]
And that's the kind of information you need to include when you report an issue. I can't make assumptions about what you have or haven't done. Please always include as much relevant information as you can think of.

So the next thing to do is to see where homebrew installed it. The default paths the loader tries to load from are listed here:

https://github.com/BindBC/bindbc-sdl/blob/master/source/bindbc/sdl/dynload.d#L43

Please check and see if SDL is installed in one of those locations, or somewhere else.

It may also help if you print the error messages instead of just asserting. Often, the system errors are no more than "failed to load library", but it's worth a try.

**Comment by joelcnz** [comment]
Yeah, I think it is to do with not finding the library. Thanks for your help.

**Comment by mdparker** [comment]
Yes. that's what the error means. So I need to figure out why. If homebrew has changed where it installs SDL on Big Sur, then I'll need to add that new path to the list of default search paths. And I need your help to determine if that's the case. Were you able to find where it is installed?

**Comment by joelcnz** [comment]
It's actually my brothers' computer. It works on my Big Sur computer like normal. He's visiting at the moment, I don't know when he leaves. Hopefully I can have another shot at it.

The following is the only place I found it on his computer. That's part of Home Brew (eg. cellar).
/usr/local/Cellar/sdl2/2.0.10/lib

**Comment by mdparker** [comment]
If it SDL isn't anywhere else on the system, then maybe the install failed? I would try to run `homebrew install` again to see what comes up. And if that turns up nothing, then `homebrew remove` followed by another install. If you see no errors doing any of that, then either SDL is being installed somewhere and you missed it, or there may be an issue with homebrew.

**Comment by joelcnz** [comment]
Home brew does treat Arm64 different than Intel installations of Big Sur. Neither say about where they install to ('brew info').

**Comment by mdparker** [comment]
So please do a search for "SDL2.framework" and/or "libSDL2.dylib".

**Comment by joelcnz** [comment]
Nothing, I don't think mac searches in a lot of the non user files.

**Comment by mdparker** [comment]
Then have a look in "/System/Library/Frameworks/" or "/usr/local/lib". I'm not a regular Mac user, and I have only cursory knowledge about homebrew and common directory trees. Maybe find out who maintains the SDL2 homebrew, or ask in a homebrew-related forum somewhere, or perhaps even in the SDL forums, if anyone knows where it gets installed.

**Comment by joelcnz** [comment]
Found these files in /opt/homebrew/lib
libSDL2-2.0.0.dylib
libSDL2.a
libSDL2.dylib

**Comment by mdparker** [comment]
> He hasn't got XCode installed.

Well that may be the problem then.

**Comment by mdparker** [comment]
At any rate, I found this:

https://stackoverflow.com/questions/28016258/using-homebrew-installed-sdl2-with-xcode

It seems the normal install path via homebrew is `/usr/local/lib`. And `brew search sdl2` should tell you where it's actually installed.

**Comment by joelcnz** [comment]
Sorry, actually he has got xcode installed.

**Comment by mdparker** [comment]
Okay then. If there's nothing in `/usr/local/lib`, I don't know if the /opt/homebrew/lib path is the install location or a cache, but I found this:

See if there's a `/opt/homebrew/bin/sdl2-config` and run that with the `--libs` switch.

**Comment by mdparker** [comment]
Okay. Solved it.

https://docs.brew.sh/Installation

> This script installs Homebrew to its preferred prefix (/usr/local for macOS Intel, /opt/homebrew for Apple Silicon and /home/linuxbrew/.linuxbrew for Linux)

So I'll need to add the '/opt/homebrew/lib/' path to the default list. For now, as a workaround, you can do this:

```d
loadSDL("/opt/homebrew/lib/libSDL2.dylib");
```
I'll push an update soonish.

**Comment by joelcnz** [comment]
I still get the same - no library error.

**Comment by mdparker** [comment]
Then try passing `loadSDL("/opt/homebrew/lib/libSDL2-2.0.0.dylib")`. And please print out the error messages if this fails.

**Comment by joelcnz** [comment]
It still fails.

I got this, trying to use sdl's get error message, (just an uninitialised object):
Program exited with code -11

**Comment by mdparker** [comment]
I meant the error messages from the bindbc loader:

https://github.com/BindBC/bindbc-loader#error-handling

That will tell us what the system reported. It will probably be useless, but still worth a try.

**Comment by joelcnz** [comment]
I can't get the error messages to work.

Error: undefined identifier `logError`

**Comment by mdparker** [comment]
That's because it's not a real function. The comment in the example says, "A hypothetical logging function".  Try this:

```d
import std.stdio, std.string;
writefln("%s: %s", fromStringz(info.error), fromStringz(info.message));
```

**Comment by joelcnz** [comment]
: dlopen(, 2): no suitable image found.  Did find:
	/usr/lib/: not a file
	/usr/lib: not a file

**Comment by mdparker** [comment]
And that was from calling load with the "opt/homebrew/lib" path? What prints when you call `loadSDL()` with no arguments?

**Comment by mdparker** [comment]
Hmm. Actually, I wonder what that bit about "/usr/lib" means. Can you see any SDL libraries in "/usr/lib"?

**Comment by joelcnz** [comment]
I see other libraries in "/usr/lib", but not SDL libraries.

It found the one I have in my test programs folder, but says not suitable.

libSDL2.dylib: dlopen(libSDL2.dylib, 2): no suitable image found.  Did find:
	libSDL2.dylib: mach-o, but wrong
/usr/local/lib/libSDL2.dylib: dlopen(/usr/local/lib/libSDL2.dylib, 2): image not found
/usr/local/lib/libSDL2/libSDL2.ddlopen(/usr/local/lib/libSDL2/libSDL2.dylib, 2): image not found: dlopen(/usr/local/lib/libSDL2/libSDL2.dylib, 2): image not found
../Frameworks/SDL2.framework/SDLdlopen(../Frameworks/SDL2.framework/SDL2, 2): image not found: dlopen(../Frameworks/SDL2.framework/SDL2, 2): image not found
/Library/Frameworks/SDL2.framewodlopen(/Library/Frameworks/SDL2.framework/SDL2, 2): image not found: dlopen(/Library/Frameworks/SDL2.framework/SDL2, 2): image not found
/System/Library/Frameworks/SDL2.dlopen(/System/Library/Frameworks/SDL2.framework/SDL2, 2): image not found: dlopen(/System/Library/Frameworks/SDL2.framework/SDL2, 2): image not found
/opt/local/lib/libSDL2.dylib: dlopen(/opt/local/lib/libSDL2.dylib, 2): image not found

I don't know how I  had the previous one with missing stuff, this is what I get with "/opt/homebrew/lib/libSDL2-2.0.0.dylib":
/opt/homebrew/lib/libSDL2-2.0.0.dlopen(/opt/homebrew/lib/libSDL2-2.0.0.dylib, 2): no suitable image found.  Did find:
	/opt/hom: dlopen(/opt/homebrew/lib/libSDL2-2.0.0.dylib, 2): no suitable image found.  Did find:
	/opt/hom

**Comment by mdparker** [comment]
Okay. I don't know what else to do for now. I'll put this on my todo list and look into it more when I can.

**Comment by joelcnz** [comment]
Ok. Thanks any way.

**Comment by mdparker** [comment]
One thing to note: the error message with the /opt path is different. Notice that they other errors say, "image not found", but for the /opt path it says, "No suitable image found". That part that says "did find" is being cut off, but that's something to look into.

**Comment by mdparker** [comment]
I've pushed a new version of bindbc-loader that should have better handling of error messages---things shouldn't get cut off now. Give it some time to propagate to the package repository, then run `dub upgrade` in the project directory to pick up the new version and print the errors again. Maybe this time with some labels to make them more coherent:

```d
writefln("Error: %s,  Message: %s", fromStringz(info.error), fromStringz(info.message));
```

**Comment by mdparker** [comment]
@joelcnz Did the new error reporting help at all?

**Comment by joelcnz** [comment]
It's my brothers computer, so I haven't had much chance to try it. I was able to spend a lot of time on it when we (me and you) were going back and forth, because my brother was watching a movie on his phone at the time, (which was unusual).

**Comment by ichordev** [comment]
If there haven't been any more updates regarding your problem then I might investigate it myself and then close this.

**Comment by MikeShah** [comment]
I think I might have had this problem regarding Mac M1 causing weird behavior with not loading.

It turned out for me the renderer was already created with the window. Anyway, here's some error checking code that may help.

`        // Create a hardware accelerated renderer                                                                              
    // It can be useful to 'clear' the errors beforehand in SDL                                                                
    SDL_ClearError();                                                                                                          
    // Pointer to our renderer                                                                                                 
    SDL_Renderer* renderer;                                                                                                    
    // On Mac's, it's possible that creating the window will also create                                                       
    // the renderer, so we should check first.                                                                                 
    if(SDL_GetRenderer(window)==null){                                                                                         
       renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_ACCELERATED);                                                    
    }else{                                                                                                                     
        renderer = SDL_GetRenderer(window);                                                                                    
    }                                                                                                                          
    // If there's still an error, then convert the const char* and write                                                       
    // out the string                                                                                                          
        if(renderer==null){                                                                                                    
        import std.conv;                                                                                                       
                writeln("renderer ERROR: ", to!string(SDL_GetError()));                                                        
        }`
