### ISSUE TITLE
Error: undefined identifier `SDL_WINDOW_ALLOW_HIGHDPI`

### ISSUE THREAD

**Issue by rillki** [BindBC/bindbc-sdl#43]
I'm dynamically loading SDL2. I see that `SDL_WINDOW_ALLOW_HIGHDPI` is defined in [sdl/bind/sdlvideo.d](https://github.com/BindBC/bindbc-sdl/blob/55ebaf3970b9a15cbfd5ef7f5c0dddf2c5f96dab/source/bindbc/sdl/bind/sdlvideo.d), but still get this error. SDL_GetVersion returns `SDL_version(2, 24, 0)`.

dub.json:
```
"dependencies": {
		"bindbc-sdl": "~>1.2.1"
	},
"versions": ["SDL2020", "SDL_Image", "SDL_TTF", "SDL_Mixer"],
```

**Comment by mdparker** [comment]
You've got the wrong version defined for SDL: `"SDL2020"` should be `"SDL_2020"`.

**Comment by rillki** [comment]
thanks, it works now.
