### ISSUE TITLE
Maybe an example?

### ISSUE THREAD

**Issue by glowiak** [BindBC/bindbc-sdl#47]
Since it is different from baseline SDL, an example would be good. I spent literally hours searching the source packages to find what to import to get SDL_Window and SDL_Renderer, and it gives no definition of struct.

**Comment by ichordev** [comment]
Hi, all you have to do is import bindbc.sdl, as shown in a couple of the examples in BindBC SDL’s README.MD:
```d
// Import the dependent package
import bindbc.sdl;
```
This is not much different from baseline SDL where you only have to include SDL.h.
In BindBC SDL 1.3.0 I’d like to have a “quick-start guide” of sorts, so I’ll try to make this a bit clearer there.

**Comment by glowiak** [comment]
Not quite, to get the window and renderer structs I needed to import bindbc.sdl.bind.sdlvideo and bindbc.sdl.bind.sdlrenderer, but it still says:
Error: variable `app.w` no definition of struct SDL_Window

**Comment by ichordev** [comment]
First of all, you are incorrect. Do not individually import the internal binding files (bindbc.sdl.bind.*), the library will not work properly if you do this.

What does your code look like and which build system do you use? (e.g. dub)

**Comment by mdparker** [comment]
`SDL_Window` is an opaque struct. In the SDL C header it's defined as:

```
typedef struct SDL_Window SDL_Window;
```

You aren't meant to access its internals. So in the binding, it's also opaque:

```
struct SDL_Window;
```

And all you need is `import bindbc.sdl`. That will pull in `bindbc.sdl.bind.sdlvideo`  (where `SDL_Window` is defined) as a public import.

**Comment by glowiak** [comment]
Removed the unneeded imports and still the same error, adding 'struct' just makes it worse'

**Comment by mdparker** [comment]
You don't need to add `struct`. Are you still trying to access the `.w` field? Again, that's not available in SDL's public API. That's what this is a binding for. You can't access `w` field. It's an internal thing. Ditto for `SDL_Renderer`. If you want the width of the window, you use `SDL_GetWindowSize`.

https://wiki.libsdl.org/SDL2/SDL_GetWindowSize

**Comment by ichordev** [comment]
@glowiak Please provide a code example. “Adding struct” and “makes it worse” are nondescript phrases that could mean almost anything.

**Comment by glowiak** [comment]
```
import std.stdio;
import std.string;

import bindbc.sdl;

const int WIDTH = 800;
const int HEIGHT = 600;
const int WFPS = 60;
const int SECOND = 1000;
const string CAPTION = "Example SDL Game";

SDL_Window w;
SDL_Renderer r;

const int DRAW_INTERVAL = SECOND/WFPS;
int _fps;
int realFps;
int timerr;

void main()
{
    SDLSupport ret = loadSDL();

    init();
}

void init()
{
    SDL_Init(SDL_INIT_EVERYTHING);
    w = SDL_CreateWindow(cast(char*)CAPTION, SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, WIDTH, HEIGHT, SDL_WINDOW_SHOWN);
    r = SDL_CreateRenderer(w, -1, SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);
}
void update()
{
}
void draw()
{
}
```

**Comment by mdparker** [comment]
> SDL_Window w;
> SDL_Renderer r;

This needs to be pointers.

Here's a working program:

```d
import bindbc.sdl;

void main()
{
    SDLSupport ret = loadSDL();
    if(ret != sdlSupport)
    {
        if(ret == SDLSupport.noLibrary) {
            throw new Exception("No library");
        }
        else if(sdlSupport == SDLSupport.badLibrary) {
            throw new Exception("Bad Library");
        }
    }
    SDL_Init(SDL_INIT_EVERYTHING);
    scope(exit) SDL_Quit();

    SDL_Window* window = SDL_CreateWindow(
        "My Window",
        SDL_WINDOWPOS_CENTERED,
        SDL_WINDOWPOS_CENTERED,
        1024, 768, SDL_WINDOW_SHOWN);

    SDL_Renderer* renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);

    SDL_Delay(3000);
}
```

Any working C code using SDL 2 should generally be a 1-to-1 match in D with these bindings. There are a few edge cases, but this is not one of them.

**Comment by mdparker** [comment]
Also, here's a little tip @glowiak . Regarding these constants:

```d
const int WIDTH = 800;
const int HEIGHT = 600;
const int WFPS = 60;
const int SECOND = 1000;
const string CAPTION = "Example SDL Game";
```

Each of these is a runtime variable. It's much more efficient in D to declare them as manifest constants like so:

```d
enum WIDTH = 800;
enum HEIGHT = 600;
enum WFPS = 60;
enum SECOND = 1000;
enum CAPTION = "Example SDL Game";
```

This makes them compile-time values. Using them is just like using pasting their values into the code. 

I removed the types because D will infer them when it sees a declaration with a storage class and no type, e.g., `enum x =` or `const y = `.

And to pass `CAPTION` to `SDL_CreateWindow`, you don't have to cast it to `char*`.  The function takes `const(char)*` anyway. Just do `CAPTION.ptr`.

**Comment by glowiak** [comment]
@mdparker Thank you, now it works. Though that there are no pointers in D, so removed the stars. Now know this was a mistake
