### ISSUE TITLE
Loading old version of SDL Mixer

### ISSUE THREAD

**Issue by elvodqa** [BindBC/bindbc-sdl#48]
I updated SDL Mixer 2.6.X recently but when I check sdlMixerSupport, it's 'sdlMixer200'. I'm using macOS. Is it because of an unimplemented binding?

**Comment by mdparker** [comment]
Did you configure the `SDL_MIXER_260` version in your dub recipe as per the README?

**Comment by elvodqa** [comment]
I changed it to SDL_MIXER_260. sdlMixerSupport returns sdlMixer260 but loadSDLMixer fails to load. I double-checked and I have sdl2_mixer 2.6.3_1 installed.

**Comment by mdparker** [comment]
What do you mean by "fails to load"? What is `loadSDLMixer` returning? Have you printed out the error messages as described in the README?

**Comment by elvodqa** [comment]
I'm sorry for not reading README carefully. Checking errors properly, SDL Mixer on my directory seems to be older. I already had 2.6.4 installed from `https://www.libsdl.org/projects/SDL_mixer/release`.
