### ISSUE TITLE
/packages/bindbc-sdl-1.4.1/bindbc-sdl/source/sdl/assert_.d-mixin-36(38,103): Error: unrecognized trait `parameters`

### ISSUE THREAD

**Issue by lilijreey** [BindBC/bindbc-sdl#55]
![image](https://github.com/BindBC/bindbc-sdl/assets/1732373/c72fbf91-f86f-4dc4-b7ae-532de1a6e8d1)

**Comment by ichordev** [comment]
This means your compiler is too old to support `__traits(parameters)`. Please update your compiler to the latest version. I was planning to try and concoct a workaround for this, but I think it'd overcomplicate the code generation.
