### ISSUE TITLE
example code in the readme cannot compile

### ISSUE THREAD

**Issue by SingingBush** [BindBC/bindbc-sdl#58]
in the example code I found the line `LoadMsg ret = loadSDL();` which should be `SDLSupport ret = loadSDL();` as it is in one of the other examples. Also the line `SDL_version version;` cannot work as _version_ is a keyword in D so I had to change the variable to v. Finally the example made use of _itoa_ which I needed to change to use the `std.conv : to` function: 

```
			SDL_version v;
			SDL_GetVersion(&v);
			msg = "Your SDL version is too low: " ~
				to!string(v.major) ~ "." ~
				to!string(v.minor) ~ "." ~
				to!string(v.patch) ~
				". Please upgrade to 2.0.16+.";
```

**Comment by ichordev** [comment]
Ah, the symbol name was a bit of an oversight. Dunno how I copied `LoadMsg` into there, though. That's something that other BindBC libraries use.

About the `msg` string: `itoa` is just a generic function that I expect to be recognisable enough to get the idea across. The example is just that, an example, not a working code sample. It already contains two calls to hypothetical functions. No copy-pastable example will meet everyone's needs, so it's just a rough illustration of how your own error handling could work.
