### ISSUE TITLE
Alias instead of function in sdlpower.d

### ISSUE THREAD

**Issue by materus213** [BindBC/bindbc-sdl#6]
In static version of sdlpower there is 
`alias pSDL_GetPowerInfo = SDL_PowerState function(int*,int*); `
instead of 
`SDL_PowerState SDL_GetPowerInfo(int*,int*);`
also
`SDL_INIT_EVERYTHING`
don't have 
`SDL_INIT_SENSOR`
for sdl209

**Comment by mdparker** [comment]
`SDL_GetPowerInfo` is fixed in 0.5.1.

`SDL_INIT_SENSOR` is there already [on line 20 of sdl.d](https://github.com/BindBC/bindbc-sdl/blob/master/source/bindbc/sdl/bind/sdl.d#L20). Did you pass version `SDL_209` to the compiler? It's not enabled by default.

**Comment by materus213** [comment]
I've meant `SDL_INIT_EVERYTHING` should be like ` ... | SDL_INIT_GAMECONTROLLER | SDL_INIT_SENSOR`

**Comment by mdparker** [comment]
Somewhere between initially reading the issue and looking into the source, that important bit fell out of my head. Fixe now in 0.6.0.
