### ISSUE TITLE
Unable to find and link to SDL2

### ISSUE THREAD

**Issue by gruelingpine185** [BindBC/bindbc-sdl#60]
I installed a project [https://github.com/yeti0904/YETI-16-Mk2](https://github.com/yeti0904/YETI-16-Mk2) and built it on MacOS which uses `bindbc-sdl v1.4.5`.

```sh
YETI-16-Mk2 main ➜ dub build --force
    Starting Performing "debug" build using ldc2 for x86_64.
    Building bindbc-common 0.1.2: building configuration [noBC]
    Building bindbc-loader 1.1.3: building configuration [noBC]
    Building bindbc-sdl 1.4.5: building configuration [dynamic]
    Building yeti-16 ~main: building configuration [application]
     Linking yeti-16
```

When running it, it errors out with the following message defined by yeti-16:

```sh
YETI-16-Mk2 main ➜ ./yeti-16 run tests/helloWorld.asm
No SDL support
Library not available
```

even though I have both SDL2 and SDL3 installed in standard locations.

```sh
YETI-16-Mk2 main ? ➜ ls /usr/local/lib | grep libSDL
libSDL2-2.0.0.dylib
libSDL2-2.0.dylib
libSDL2.a
libSDL2.dylib
libSDL2.la
libSDL2_test.a
libSDL2_test.la
libSDL2main.a
libSDL2main.la
libSDL3.1.0.0.dylib
libSDL3.dylib
libSDL3_test.a
YETI-16-Mk2 main ? ➜
```

What got the program to work was creating a symlink to `/usr/local/lib/libSDL2.dylib` and placing that in the same directory as the executable.

---
I can't really provide much more info than this because I'm not proficient with D not am I the creator of Yeti-16.

**Comment by ichordev** [comment]
The issue is that `/usr/local/lib` isn’t a default library search path in modern macOS. You can either symlink your library to somewhere else that’s supported by default, or you can add `/usr/local/lib` to your library path environment variable in your shell startup script. I use Homebrew to install things like SDL, which is manually supported in BindBC-SDL.
