### ISSUE TITLE
SDL_MouseButtonEvent.button has wrong type

### ISSUE THREAD

**Issue by Herringway** [BindBC/bindbc-sdl#70]
According to https://wiki.libsdl.org/SDL3/SDL_MouseButtonEvent, SDL_MouseButtonEvent.button should either be a ubyte or SDL_MouseButton should be changed to a ubyte instead of an int.

**Comment by ichordev** [comment]
https://github.com/BindBC/bindbc-sdl/commit/f8e9da3d89e1aa51010e06f10a61b6e6ae91a104: Easily fixed! :)
