### ISSUE TITLE
Cant install `~>2.0`

### ISSUE THREAD

**Issue by Bizarrus** [BindBC/bindbc-sdl#72]
# Installation like in `Readme`
> dub add bindbc-sdl

**Result:**
``` 
  Adding dependency bindbc-sdl ~>1.5.0
```

> [!TIP]
> Bad Version! Its not 2.0, its 1.5.0!

# Trying `~master`
> dub add bindbc-sdl@~master

**Result:**
``` 
  Adding dependency bindbc-sdl ~master
```

> [!CAUTION]
> Warning Dependency 'bindbc-sdl' depends on git branch '~master', which is deprecated.
> Specify the git repository and commit hash in your dub.json:
> "bindbc-sdl": {"repository": "git+<git url>", "version": "<commit>"}
> Warning Selected package bindbc-sdl@1.0.1 does not match the dependency specification ~master in package mb-client. Need to "dub upgrade"?

# Trying `~2.0`
> dub add bindbc-sdl@~>2.0

**Result:**
``` 
  Adding dependency bindbc-sdl ~>2
```

> [!CAUTION]
> Error Unresolvable dependencies to package bindbc-sdl:
> mb-client ~master depends on bindbc-sdl ~>2

# Manual installation over `dub.json`
```
"dependencies": {
	"bindbc-sdl": "~>2.0"
},
```

> dub upgrade

> [!CAUTION]
> Error Unresolvable dependencies to package bindbc-sdl:
> mb-client ~master depends on bindbc-sdl ~>2

**Comment by ichordev** [comment]
There is no v2.0, there are only pre-releases of it: https://github.com/BindBC/bindbc-sdl/tags
The readme is written as if SDL 3.2.0 is out, which it isn’t. Until then, there will only be pre-releases.

**Comment by Bizarrus** [comment]
> There is no v2.0, there are only pre-releases of it: https://github.com/BindBC/bindbc-sdl/tags The readme is written as if SDL 3.2.0 is out, which it isn’t. Until then, there will only be pre-releases.

Then, the [Quick Start Guide](https://github.com/BindBC/bindbc-sdl?tab=readme-ov-file#quickstart-guide) is not correct.

I've open this issue, because its in the docs!

**Comment by ichordev** [comment]
> Then, the [Quick Start Guide](https://github.com/BindBC/bindbc-sdl?tab=readme-ov-file#quickstart-guide) is not correct.
> 
> I've open this issue, because its in the docs!

The readme is intentionally written as if SDL3 (and therefore BindBC-SDL v2.0) is already out so that it will be correct then without being rewritten again. This is mentioned in the disclaimer at the top of the readme. The readme also currently refers to a hypothetical SDL v3.4 in case you didn’t notice…
